In [ ]:
# 서울시 외국인 주민인구에 대한 분석
# 실시간 유동인구가 아닌 거주신고를 한 경우를 센 것임

In [30]:
import pandas as pd
file_dir = "C://Users/Youngju Hong/Documents/projectfile/"

In [ ]:
##1. 주민등록인구 핸들링 (외국인 주민인구의 경우 (국적이 병기되어 있는 경우) 구단위 인구밖에 존재하지 않음)

In [50]:
local_data = pd.read_table(f"{file_dir}서울시 주민등록인구 (구별) 통계.txt", sep = '\t')
local_data = local_data.iloc[3:len(local_data), [1,3]]
local_data.columns = ["gu", "population"]
local_data.head()

    gu population
3  종로구    161,984
4   중구    136,469
5  용산구    246,165
6  성동구    307,193
7  광진구    365,990

In [39]:
#생활인구
foreign_data = pd.read_excel(f"{file_dir}foreign_living_population_by_gu.xlsx")
foreign_data.head()

,Unnamed: 0,gu,time,fornlong_spop,chn,vnm,usa,jpn,can,twn,etcsum
0,0,강남구,Day,25307.578622,13289.960152,536.864218,4506.660898,707.090323,1487.164507,408.956929,4370.880649
1,1,강남구,Night,16133.034599,7041.030400,392.502755,3841.991750,445.573409,1283.156815,223.441581,2905.337030
2,2,강동구,Day,9339.953392,7089.004106,194.506633,581.818045,138.942865,201.187246,48.235230,1086.258718
3,3,강동구,Night,10037.885859,7644.061806,198.229610,660.657754,145.090763,222.103401,49.028630,1118.713444
4,4,강북구,Day,4978.363737,3271.037058,320.429063,235.637500,141.699527,66.473585,51.748397,891.338131

In [40]:
#생활인구
merged = pd.merge(local_data, foreign_data, on = "gu")
del merged["Unnamed: 0"]
merged.head()

,gu,population,time,fornlong_spop,chn,vnm,usa,jpn,can,twn,etcsum
0,종로구,"161,984",Day,17029.882213,10454.344980,1133.083452,1042.693486,361.127909,356.618154,430.207062,3251.806905
1,종로구,"161,984",Night,14695.707296,9328.651346,1105.101633,828.937039,226.571224,294.863398,326.720127,2584.862266
2,중구,"136,469",Day,23141.216466,15250.827103,931.451610,1074.638448,487.794376,495.336772,861.014100,4040.153865
3,중구,"136,469",Night,17142.188349,11226.673409,894.488975,763.816191,258.684343,358.050298,661.851904,2978.623128
4,용산구,"246,165",Day,22895.056582,5910.923214,341.779900,3982.602431,947.517986,829.195254,435.208553,10447.829107

In [46]:
#주민등록인구
foreign_living_data = pd.read_table(f"{file_dir}foreign_reg_population.txt")
foreign_living_data = foreign_living_data.replace({',': '', ' ': '', '-': 0}, regex = True)
foreign_living_data.columns = foreign_living_data.columns.str.replace(' ', '')
foreign_living_data = foreign_living_data[foreign_living_data["성별"] == "계"]

In [47]:
#foreign_living_data (주민등록인구) 데이터 처리
foreign_living_data["chn_reg"] = foreign_living_data.loc[:, ["한국계중국인","중국(한국계중국인제외)"]].astype(float).sum(axis = 1) #형변환
foreign_data_revised = foreign_living_data[["자치구", "합계", "미국", "타이완", "일본", "베트남", "캐나다", "chn_reg"]] #특정 열 선택
foreign_data_revised

     자치구      합계    미국   타이완    일본    베트남   캐나다   chn_reg
0     합계  280126  9762  8486  8331  19650  1544  178623.0
3    종로구   10767   380   257   293   2100    30    5417.0
6     중구   10294   276   563   242   1360    66    4487.0
9    용산구   16586  2504   351  1274    313   235    1943.0
12   성동구    8151   239   173   154   1010    52    4793.0
15   광진구   15573   187   127   317   1389    42   10604.0
18  동대문구   16637   237   314   469   2448    50    9544.0
21   중랑구    5059    63    70   139    664    20    2353.0
24   성북구   12038   359   279   333   1407    71    6101.0
27   강북구    3765    85   103   118    571    16    1909.0
30   도봉구    2257    73    41   110    361    14     899.0
33   노원구    4458   199    97   203   1032    45    1589.0
36   은평구    4490   136   553   373    559    37    2028.0
39  서대문구   13233   727  2269   564   1161   111    5467.0
42   마포구   11516  1142  1365   937    529   109    4755.0
45   양천구    4193   129   187   120    312    28    2495.0
48   강서구    6401   219   315   331    418    69    3600.0
51   구로구   32471    91   179   195    519    29   30362.0
54   금천구   18787    44    77   116    420    16   17383.0
57  영등포구   32863   222   371   231    322    42   30416.0
60   동작구   12788   195   139   184   1011    31    9840.0
63   관악구   17288   312   164   367    749    56   12656.0
66   서초구    4233   558   136   284    124    90    1250.0
69   강남구    5094   786   155   464    212   152    1693.0
72   송파구    6788   438   139   339    325    99    4223.0
75   강동구    4396   161    62   174    334    34    2816.0

In [48]:
foreign_data_revised = foreign_data_revised.rename({"미국": "usa_reg", "타이완": "twn_reg", "일본": "jpn_reg", "캐나다": "can_reg", "베트남": "vnm_reg"}, axis = 1)
foreign_data_revised["major_sum"] = foreign_data_revised.loc[:,"usa_reg":"chn_reg"].astype(float).sum(axis = 1)
foreign_data_revised["etcsum"] = foreign_data_revised["합계"].astype(float).subtract(foreign_data_revised["major_sum"])
foreign_data_revised = foreign_data_revised.rename(columns = {"자치구": "gu", "etcsum": "etcsum_reg"})
foreign_data_revised

,gu,합계,usa_reg,twn_reg,jpn_reg,vnm_reg,can_reg,chn_reg,major_sum,etcsum_reg
0,합계,280126,9762,8486,8331,19650,1544,178623.0,226396.0,53730.0
3,종로구,10767,380,257,293,2100,30,5417.0,8477.0,2290.0
6,중구,10294,276,563,242,1360,66,4487.0,6994.0,3300.0
9,용산구,16586,2504,351,1274,313,235,1943.0,6620.0,9966.0
12,성동구,8151,239,173,154,1010,52,4793.0,6421.0,1730.0
15,광진구,15573,187,127,317,1389,42,10604.0,12666.0,2907.0
18,동대문구,16637,237,314,469,2448,50,9544.0,13062.0,3575.0
21,중랑구,5059,63,70,139,664,20,2353.0,3309.0,1750.0
24,성북구,12038,359,279,333,1407,71,6101.0,8550.0,3488.0
27,강북구,3765,85,103,118,571,16,1909.0,2802.0,963.0
30,도봉구,2257,73,41,110,361,14,899.0,1498.0,759.0
33,노원구,4458,199,97,203,1032,45,1589.0,3165.0,1293.0
36,은평구,4490,136,553,373,559,37,2028.0,3686.0,804.0
39,서대문구,13233,727,2269,564,1161,111,5467.0,10299.0,2934.0
42,마포구,11516,1142,1365,937,529,109,4755.0,8837.0,2679.0
45,양천구,4193,129,187,120,312,28,2495.0,3271.0,922.0
48,강서구,6401,219,315,331,418,69,3600.0,4952.0,1449.0
51,구로구,32471,91,179,195,519,29,30362.0,31375.0,1096.0
54,금천구,18787,44,77,116,420,16,17383.0,18056.0,731.0
57,영등포구,32863,222,371,231,322,42,30416.0,31604.0,1259.0
60,동작구,12788,195,139,184,1011,31,9840.0,11400.0,1388.0
63,관악구,17288,312,164,367,749,56,12656.0,14304.0,2984.0
66,서초구,4233,558,136,284,124,90,1250.0,2442.0,1791.0
69,강남구,5094,786,155,464,212,152,1693.0,3462.0,1632.0
72,송파구,6788,438,139,339,325,99,4223.0,5563.0,1225.0
75,강동구,4396,161,62,174,334,34,2816.0,3581.0,815.0

In [256]:
merged = pd.merge(merged, foreign_data_revised, on = "gu")
merged.to_excel("final.xlsx")