In [5]:
#좌표변환, EPSG:5179로 일괄 적용
from pyproj import Proj, Transformer, CRS
from functools import partial
import pandas as pd
import requests

1. transformer = Transformer.from_crs를 활용하여 좌표를 변환해줄 객체 생성
2. transformer(y축 좌표, x축 좌표) >> 반환값은 튜플

3. transformation 함수: epsg_from, epsg_to, x_coordinate, y_coordinate

In [6]:
def transformation(x_coordinate, y_coordinate, epsg_from = 4326, epsg_to = 5179):
    return Transformer.from_crs(f"epsg:{epsg_from}", f"epsg:{epsg_to}").transform(y_coordinate, x_coordinate)

In [7]:
def address_retrival(keyword, size = 1, epsg = 5179):
    url = f"http://api.vworld.kr/req/search?service=search&request=search&\
            &size={size}&page=1&query={keyword}&type=place&format=json&errorformat=json&crs=EPSG:{epsg}\
                &key=8FEEBFAF-A069-393A-B997-411AA9884913"
    result = requests.get(url).json()["response"]
    if result["status"] in ("NOT_FOUND", "ERROR"):
        return None
    
    elif size == 1:
        result = result["result"]["items"][0]
        return {"검색어": keyword, "주소": result["address"]["parcel"], "X": result["point"]["x"], "Y": result["point"]["y"]}
    
    else: # size > 1: 여러개의 검색 결과를 return할 경우
        for i in result["result"]["items"]:
            print(f"검색어: {i['title']}, 주소: {i['address']['parcel']}, 좌표: {i['point']['x'], i['point']['y']}")
            answer =  input("Take or Leave - 1/0")
            if answer == "1":
                return [i['title'], i['address']['parcel'], i['point']['x'], i['point']['y']]

In [8]:
address_retrival("경희대학교", size = 1)

{'검색어': '경희대학교',
 '주소': '경기도 용인시 기흥구 서천동 1번지',
 'X': '962646.655018903',
 'Y': '1916309.115452343'}

In [9]:
def address_retrival_df(size = 5, epsg = 5179): #return by dataframe
    searched_address = pd.DataFrame(columns = ["검색 키워드", "주소", "위도", "경도"])
    count = 0
    while True:
        print("Input a keyword for search: type nothing for quit.")
        keyword = input()
        if keyword == "":
            return searched_address
        url = f"http://api.vworld.kr/req/search?service=search&request=search&\
                &size={size}&page=1&query={keyword}&type=place&format=json&errorformat=json&crs=EPSG:{epsg}\
                    &key=8FEEBFAF-A069-393A-B997-411AA9884913"
        result = requests.get(url).json()["response"]
        if result["status"] in ("NOT_FOUND", "ERROR"):
            print("Result not found")
        else: # size > 1: 여러개의 검색 결과를 return할 경우
            print("Results: Choose your option.")
            for i in result["result"]["items"]:
                print(f"검색어: {i['title']}, 주소: {i['address']['parcel']}, 좌표: {i['point']['x'], i['point']['y']}")
                answer =  input("Input T for take")
                if answer == "T":
                    searched_address[count] = [i['title'], i['address']['parcel'], i['point']['x'], i['point']['y']]
                    count += 1

In [ ]:
address_retrival_df()

In [10]:
data = pd.read_excel("/Users/hong/Downloads/traffic_accident.xlsx", encoding = "cp949")

In [21]:
data.columns
len(data)

250

In [16]:
gps = list(zip(data[" GPS_X"], data[" GPS_Y"]))

In [22]:
transformed = []
for i in gps:
    transformed.append(transformation(i[0], i[1]))
    print(transformed[-1])

In [25]:
data["X_modified"], data["Y_modified"] = [i[0] for i in transformed], [i[1] for i in transformed]

In [26]:
data.to_excel("accident_with_transformed_coordinate.xlsx")

In [27]:
data = pd.read_csv("/Users/hong/Documents/GitHub/seoulresearch_project/department_store.csv", encoding = "cp949")
data
#EPSG:2097

,Unnamed: 0,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,...,도로명주소,도로명우편번호,사업장명,최종수정일자,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),점포구분명
0,48,3010000,2.012300e+18,19791227,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 중구 남대문로 81 (소공동),100721.0,롯데백화점 본점,2.017080e+13,I,2018.8.31 23:59,백화점,198259.6536,451392.1982,대규모점포
1,75,3010000,2.005300e+18,19731030,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 중구 남대문로 67 (남대문로2가),NaN,롯데쇼핑본점영플라자,2.020040e+13,U,2020.5.2 2:40,백화점,198315.5327,451248.1416,대규모점포
2,107,3020000,2.006300e+18,20060825,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 용산구 한강대로23길 55 (한강로3가),140780.0,아이파크(I PARK)백화점,2.019070e+13,U,2019.7.19 2:40,백화점,196762.0774,447480.0396,대규모점포
3,126,3030000,2.005300e+18,20050331,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 뚝섬로 379,133120.0,(주)이마트 성수점,2.020050e+13,U,2020.5.3 2:40,백화점,204614.2727,448607.4413,대규모점포
4,166,3040000,2.008300e+18,20080822,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 광진구 능동로 92 (자양동),143854.0,롯데백화점 건대스타시티점,2.018070e+13,I,2018.8.31 23:59,백화점,206217.4347,448506.2187,대규모점포
5,178,3050000,2.010310e+18,20100723,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 동대문구 왕산로 214 (전농동),130851.0,롯데백화점 청량리역사점,2.017070e+13,I,2018.8.31 23:59,백화점,204081.2821,453187.3952,대규모점포
6,266,3070000,2.001310e+18,20010811,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 성북구 동소문로 315 (길음동 현대백화점미아점),136719.0,현대백화점 미아점,2.020040e+13,U,2020.4.24 2:40,백화점,202466.8011,456227.5717,대규모점포
7,307,3080000,2.006310e+18,20061214,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강북구 도봉로 62 (미아동),142804.0,롯데백화점 미아점,2.017040e+13,I,2018.8.31 23:59,백화점,202625.6463,456875.9740,대규모점포
8,350,3100000,2.005310e+18,20050826,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 노원구 동일로 1414 (상계동),139708.0,롯데백화점 노원점,2.020050e+13,U,2020.5.24 2:40,백화점,205320.2848,461419.8818,대규모점포
9,352,3100000,2.007310e+18,20070419,NaN,1,영업/정상,1,정상영업,NaN,...,NaN,NaN,건영옴니백화점,2.015030e+13,I,2018.8.31 23:59,백화점,205645.8920,459609.0125,대규모점포
10,411,3120000,1.992310e+18,19921119,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 서대문구 신촌로 83 (창천동),NaN,현대백화점 신촌점,2.017070e+13,I,2018.8.31 23:59,백화점,194265.0676,450433.6910,대규모점포
11,461,3140000,2.002310e+18,20020809,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 양천구 목동동로 257 (목동),NaN,현대백화점목동점,2.020040e+13,U,2020.4.26 2:40,백화점,188884.0756,447186.8886,대규모점포
12,462,3140000,2.004310e+18,20040604,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 양천구 목동동로 309 (목동),NaN,행복한백화점,2.019020e+13,U,2019.2.15 2:40,백화점,188977.1711,447466.3550,대규모점포
13,495,3150000,2.011320e+18,20110919,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강서구 강서로56길 17 (등촌동),157930.0,(주) 이랜드리테일 강서점,2.020020e+13,U,2020.3.1 2:40,백화점,185824.4285,450866.2521,대규모점포
14,558,3160000,2.011320e+18,20110810,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 구로구 경인로 662 (신도림동),152888.0,주식회사 현대백화점 디큐브시티,2.020050e+13,U,2020.5.28 2:40,백화점,190107.0454,445157.6264,대규모점포
15,595,3180000,1.991320e+18,19910501,NaN,1,영업/정상,1,정상영업,NaN,...,NaN,NaN,롯데백화점 영등포점,2.020040e+13,U,2020.4.16 2:40,백화점,191741.3458,445970.3076,대규모점포
16,610,3180000,2.020320e+18,20200102,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 영등포구 여의대로 108 (여의도동),7335.0,현대백화점 여의도점,2.020050e+13,U,2020.5.10 2:40,백화점,193592.0004,447092.6294,대규모점포
17,686,3200000,2.012320e+18,19971107,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 봉천로 209,151718.0,롯데쇼핑(주) 관악점,2.017040e+13,I,2018.8.31 23:59,백화점,193301.8858,443151.5613,대규모점포
18,713,3210000,2.012320e+18,20120514,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 서초구 잠원로 37-6 (잠원동 뉴코아백화점빌딩),137711.0,뉴코아백화점,2.020030e+13,U,2020.3.7 2:40,백화점,200367.9850,445207.6635,대규모점포
19,736,3210000,2.005320e+18,20150922,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 서초구 신반포로 176 (반포동),NaN,신세계백화점 강남점,2.020050e+13,U,2020.5.23 2:40,백화점,200250.4478,444683.2205,대규모점포
20,741,3220000,2.001320e+18,19850708,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강남구 압구정로 407 (압구정동 갤러리아백화점),135902.0,갤러리아백화점(동관),2.018010e+13,I,2018.8.31 23:59,백화점,203604.7617,447316.2228,대규모점포
21,749,3220000,2.001320e+18,20000616,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강남구 도곡로 401 (대치동),135704.0,롯데백화점(강남점),2.017040e+13,I,2018.8.31 23:59,백화점,204669.5434,443873.6212,대규모점포
22,762,3220000,2.011320e+18,20110412,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강남구 도산대로 442 (청담동),135948.0,SSG Food Market 백화점,2.020050e+13,U,2020.5.20 2:40,백화점,203789.5881,446796.1283,대규모점포
23,783,3220000,2.001320e+18,19851130,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강남구 압구정로 165 (압구정동 현대백화점본점),135724.0,(주)현대백화점 본점,2.020040e+13,U,2020.4.23 2:40,백화점,202358.5057,447232.9557,대규모점포
24,784,3220000,2.001320e+18,19881010,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강남구 테헤란로 517 (삼성동 무역센터현대백화점),135730.0,현대백화점 무역센터점,2.020040e+13,U,2020.4.22 2:40,백화점,205210.3588,445154.4223,대규모점포
25,785,3220000,2.001320e+18,19850318,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강남구 압구정로 343 (압구정동 갤러리아백화점),135902.0,갤러리아백화점(서관),2.018010e+13,I,2018.8.31 23:59,백화점,203470.8484,447369.5799,대규모점포
26,832,3230000,1.998320e+18,19881112,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 송파구 올림픽로 240 (잠실동),138721.0,롯데백화점 잠실점,2.017070e+13,I,2018.8.31 23:59,백화점,208589.3633,445455.9041,대규모점포
27,843,3230000,2.014320e+18,20140717,NaN,1,영업/정상,1,정상영업,NaN,...,NaN,NaN,롯데백화점 에비뉴엘 월드타워점,2.017040e+13,I,2018.8.31 23:59,백화점,209074.9008,445657.8093,대규모점포
28,873,3240000,1.999320e+18,19990412,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 강동구 천호대로 1005 (천호동 현대백화점),134779.0,현대백화점 천호점,2.020050e+13,U,2020.5.6 2:40,백화점,210931.6435,448522.0798,대규모점포
29,914,3010000,2.010300e+18,19730410,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 중구 소공로 63 (충무로1가신세계백화점건물),NaN,신세계백화점,2.020060e+13,U,2019.12.5 23:09,백화점,198263.9084,450960.7630,NaN
30,916,3160000,2.020320e+18,20200626,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 구로구 구로중앙로 152 (구로동),8292.0,이랜드리테일 NC구로점,2.020060e+13,I,2019.12.5 22:08,백화점,189570.3609,444336.0513,NaN
31,917,3180000,2.009320e+18,19821215,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 영등포구 영중로 9 (영등포동4가 신세계백화점),150985.0,(주)신세계 타임스퀘어점,2.020060e+13,U,2019.12.7 0:02,백화점,191581.5003,446108.8072,NaN
32,41,3010000,2.010300e+18,20000821,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 중구 남대문시장10길 2 (회현동1가메사빌딩),NaN,신세계백화점메사점,2.020050e+13,U,2020.5.8 2:40,쇼핑센터,198129.4355,450900.2397,대규모점포
33,389,3110000,2.007310e+18,20070411,NaN,1,영업/정상,1,정상영업,NaN,...,서울특별시 은평구 불광로 20 (대조동),NaN,엔씨백화점 불광점,2.020020e+13,U,2020.2.29 2:40,쇼핑센터,193661.7324,456379.1939,대규모점포

In [29]:
coordinate = list(zip(data["좌표정보(X)"], data["좌표정보(Y)"]))

for i in range(len(coordinate)):
    coordinate[i] = tuple(transformation(coordinate[i][0], coordinate[i][1], 2097))
    print(coordinate[i])

(1951844.4621736484, 953917.7425304065)
(1951700.1646796213, 953972.8312540945)
(1947941.834086586, 952399.9035521937)
(1949026.9398947011, 960254.9751376705)
(1948917.2138297772, 961856.9499623685)
(1953607.8903336488, 959746.6207896504)
(1956655.4606637498, 958149.0121530693)
(1957302.7549014518, 958311.2551073206)
(1961830.4401634089, 961029.07870955)
(1960018.5635059082, 961344.8793525785)
(1950907.6336599824, 949919.6196218834)
(1947690.7763597586, 944523.4143578534)
(1947969.638775868, 944617.963107668)
(1951385.0350322532, 941484.5564292478)
(1945655.7836155575, 945735.1005649744)
(1946459.4438161917, 947373.0954856469)
(1947571.4679085843, 949229.0075883145)
(1943633.4859106583, 948918.0154917678)
(1945651.148964045, 955992.2754497917)
(1945127.5409135325, 955871.9919605596)
(1947741.6210464984, 959238.9895418758)
(1944294.7339568397, 960285.0055851737)
(1947220.7509409608, 959420.9705069091)
(1947665.0278554435, 957992.7900327718)
(1945572.1382770708, 960832.4234747335)
(1947795.670241909, 959105.4143759088)
(1945855.5007676405, 964211.6633169092)
(1946054.7374931509, 964698.078301191)
(1948907.943664785, 966569.3225309179)
(1951413.1752802543, 953919.6949365756)
(1944837.3848154924, 945194.2481578217)
(1946598.7410654642, 947214.0499849176)
(1951353.393029215, 953784.9525797993)
(1956854.026522931, 949348.2411354592)

In [30]:
data["X_modified"], data["Y_modified"] = [i[0] for i in coordinate], [i[1] for i in coordinate]

In [31]:
data.to_csv("department_store.csv", encoding = "cp949")