In [4]:
import pandas as pd
directory = "C:/Users/Youngju Hong/Downloads"

In [48]:
data = pd.read_excel(f"{directory}/2019 고등교육기관 외국인 유학생 현황.xlsx", sheet_name = 2,header = 1)

In [49]:
data

,연도,학제,학교명,학교상태,본분교,시도,시군구,설립,총계,학위과정,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,공동운영\n교육과정,연수과정,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,대학·전문대학,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,계,...,공학,자연,의학,예체능,NaN,계,어학연수생,교환연수생,방문연수생,기타연수생
2,2019.0,대학교,강릉원주대학교,기존,본교,강원,강원 강릉시,국립,205.0,115,...,0,0,0,0,1.0,89,64,25,0,0
3,2019.0,대학교,강릉원주대학교,기존,제2캠퍼스,강원,강원 원주시,국립,1.0,1,...,0,0,0,0,0.0,0,0,0,0,0
4,2019.0,일반대학원,강릉원주대학교대학원,기존,본교,강원,강원 강릉시,국립,56.0,0,...,3,6,1,9,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,2019.0,기능대학,한국폴리텍대학 인천캠퍼스,기존,본교,인천,인천 부평구,사립,2.0,2,...,0,0,0,0,0.0,0,0,0,0,0
1044,2019.0,기능대학,한국폴리텍 IV 대학 대전캠퍼스,기존,본교,대전,대전 동구,사립,1.0,1,...,0,0,0,0,0.0,0,0,0,0,0
1045,2019.0,기능대학,한국폴리텍 Ⅵ 대학 영주캠퍼스,기존,본교,경북,경북 영주시,사립,3.0,3,...,0,0,0,0,0.0,0,0,0,0,0
1046,2019.0,기능대학,한국폴리텍대학 창원캠퍼스,기존,본교,경남,경남 창원시,사립,1.0,1,...,0,0,0,0,0.0,0,0,0,0,0
1047,2019.0,기능대학,한국폴리텍 VII 대학 울산캠퍼스,기존,본교,울산,울산 중구,사립,2.0,2,...,0,0,0,0,0.0,0,0,0,0,0

In [50]:
data = data[data.iloc[:,5] == "서울"]

In [51]:
def subset_name(univ):
    return univ[:univ.find("대학교")+3]

In [52]:
data["학교명"] = data["학교명"].apply(subset_name)

C:\Users\Youngju Hong\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [55]:
#data = data.groupby("학교명")["총계"].sum().reset_index()
data = data.rename(columns = {"학교명"})

               학교명      총계
0           가톨릭대학교    63.0
1         감리교신학대학교    17.0
2         개신대학원대학교   109.0
3            건국대학교  2685.0
4            경기대학교   589.0
..             ...     ...
81        한양사이버대학교    63.0
82         한양여자대학교    71.0
83           호서대학교    10.0
84           홍익대학교  2067.0
85  횃불트리니티신학대학원대학교    74.0

[86 rows x 2 columns]

In [69]:
univ = pd.read_csv(f"{directory}/서울시 대학 DB.csv", encoding = "cp949")

In [70]:
univ

,키값,연도,학교종류,학교명,본분교,학교상태,설립,우편번호,주소,도로명주소,행정시,행정구,행정동,전화번호,팩스번호,홈페이지
0,BE_LiST23-0034,2013,일반대학,서울시립대학교,본교,기존,공립,NaN,서울 동대문구 서울시립대로 163 (전농동 90번지),NaN,서울특별시,동대문구,휘경2동,02-6490-6114,02-2210-5576,http://www.uos.ac.kr
1,BE_LiST23-0035,2013,전문대학(3년제),서울여자간호대학교,본교,기존,사립,NaN,서울 서대문구 홍제3동 서울여자간호대학,NaN,서울특별시,서대문구,홍제2동,02-2287-1700,02-395-8018,http://www.snjc.ac.kr
2,BE_LiST23-0036,2013,일반대학,서울여자대학교,본교,기존,사립,NaN,서울특별시 노원구 화랑로 621 서울여자대학교,NaN,서울특별시,노원구,공릉2동,02-970-5114,02-978-7931,http://www.swu.ac.kr
3,BE_LiST23-0037,2013,전문대학(2년제),서일대학교,본교,학교명 변경,사립,NaN,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,NaN,서울특별시,중랑구,면목제3.8동,02-490-7300,02-493-2576,http://www.seoil.ac.kr
4,BE_LiST23-0038,2013,일반대학,성공회대학교,본교,기존,사립,NaN,서울 구로구 항동 성공회대학교,NaN,서울특별시,구로구,오류2동,02-2610-4142,02-2610-4248,http://www.skhu.ac.kr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,BE_LiST23-0029,2013,교육대학,서울교육대학교,본교,기존,국립,NaN,서울 서초구 서초중앙로 96(서초동 1650),NaN,서울특별시,서초구,서초1동,02-3475-2114,02-581-7711,http://www.snue.ac.kr
57,BE_LiST23-0030,2013,일반대학,서울기독대학교,본교,기존,사립,NaN,서울 은평구 갈현로 4길 26-2호,NaN,서울특별시,은평구,신사1동,02-380-2500,02-380-2535,http://www.scu.ac.kr
58,BE_LiST23-0031,2013,일반대학,서울대학교,본교,기존,국립대법인,NaN,서울 관악구 관악로 1 서울대학교,NaN,서울특별시,관악구,낙성대동,02-880-5114,02-885-5272,http://www.snu.ac.kr
59,BE_LiST23-0032,2013,사이버대학(대학),서울디지털대학교,본교,기존,사립,NaN,서울 마포구 도화동 560번지,NaN,서울특별시,마포구,도화동,02-1644-0982,02-2128-3006,http://www.sdu.ac.kr
60,BE_LiST23-0033,2013,사이버대학(대학),서울사이버대학교,본교,기존,사립,NaN,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,NaN,서울특별시,강북구,미아동,02-944-5000,02-980-2222,http://www.iscu.ac.kr

In [71]:
univ = univ.merge(data, how = "inner", on = "학교명")

In [73]:
univ = univ[univ["총계"] >= 100]

In [76]:
univ.to_excel("C:\\Users\Youngju Hong\Documents\GitHub\seoulresearch_project\대학정보.xlsx")